server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: 192.168.78.6
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/